FROM ubuntu:noble-20241015
ARG DEBIAN_FRONTEND=noninteractive

LABEL org.opencontainers.image.source=https://github.com/lwmacct/250210-cr-buildx
LABEL org.opencontainers.image.description="docker buildx 模板"
LABEL org.opencontainers.image.licenses=MIT
